chore: fix all input processors
asyncapi/generator-model-sdk pull request #30
Opened 2021-02-03 16:52 UTC by jonaslagoni

**Description**
This PR fixes all the processor tests.

2021-02-03 16:56 UTC, jonaslagoni reviewed
Do you think it makes sense to have the `InputProcessor` which simplifies everything where you dont need to know the input type?

2021-02-03 16:56 UTC, jonaslagoni commented on src/processors/JsonSchemaInputProcessor.ts
> +    isForMe(input: any): boolean {
I am not sure I like the name... But cant come up with something else.

2021-02-03 16:56 UTC, jonaslagoni commented on src/processors/InputProcessor.ts
> +    this.addProcessor("default", jsonSchema);
I could not find any other way to add a default processor while still making it changeable.

2021-02-04 15:12 UTC, magicmatatjahu requested changes

2021-02-04 15:12 UTC, jonaslagoni commented on src/processors/AsyncAPIInputProcessor.ts
> +    isForMe(input: any) : boolean {
Agreed!

2021-02-04 15:13 UTC, jonaslagoni commented on src/processors/InputProcessor.ts
> +  processors: {[key: string]: AbstractInputProcessor} = {};
I hate working with Map... 🤷

2021-02-04 15:16 UTC, magicmatatjahu commented on src/processors/InputProcessor.ts
> +  processors: {[key: string]: AbstractInputProcessor} = {};
Well then

2021-02-04 15:20 UTC, jonaslagoni commented on src/processors/InputProcessor.ts
> +  processors: {[key: string]: AbstractInputProcessor} = {};
Nwm, I just thought I could not iterate entries easily, that was a lie, changing it back 😄

2021-02-04 15:22 UTC, magicmatatjahu commented on src/processors/InputProcessor.ts
> +  processors: {[key: string]: AbstractInputProcessor} = {};
You can make `for (const [key, value] of processors) {}`

2021-02-04 15:24 UTC, magicmatatjahu commented on src/generators/AbstractGenerator.ts
> +  processor = new InputProcessor();
You didn't change it :P

2021-02-04 18:46 UTC, magicmatatjahu approved these changes

2021-02-04 18:47 UTC, merged